### List all excuses
GET http://localhost:5000/api/excuses
Content-Type: application/json

{}

### CREATE EXCUSE
POST http://localhost:5000/api/create
Content-Type: application/json

{
    "tag": "Test-msg",
    "message": "A new excuse will be created"
}

### RANDOM EXCUSE
GET http://localhost:5000/api/random
Content-Type: application/json

{}
